CREATE TABLE BRAIN_WAVE_DBA_INTERN.STUDENTS 
   (	STUDENT_ID NUMBER, 
	FIRST_NAME VARCHAR2(100), 
	LAST_NAME VARCHAR2(100), 
	DATE_OF_BIRTH DATE, 
	GENDER VARCHAR2(10), 
	EMAIL VARCHAR2(150), 
	PHONE_NUMBER VARCHAR2(15), 
	 PRIMARY KEY (STUDENT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS; 

  CREATE TABLE BRAIN_WAVE_DBA_INTERN.SUBJECTS 
   (	SUBJECT_ID NUMBER, 
	SUBJECT_NAME VARCHAR2(100), 
	 PRIMARY KEY (SUBJECT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS;

  CREATE TABLE BRAIN_WAVE_DBA_INTERN.TEACHERS 
   (	TEACHER_ID NUMBER, 
	FIRST_NAME VARCHAR2(100), 
	LAST_NAME VARCHAR2(100), 
	SUBJECT_ID NUMBER, 
	PHONE_NUMBER VARCHAR2(15), 
	EMAIL VARCHAR2(150), 
	 PRIMARY KEY (TEACHER_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE, 
	 FOREIGN KEY (SUBJECT_ID)
	  REFERENCES BRAIN_WAVE_DBA_INTERN.SUBJECTS (SUBJECT_ID) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS;

  CREATE TABLE BRAIN_WAVE_DBA_INTERN.CLASSES 
   (	CLASS_ID NUMBER, 
	CLASS_NAME VARCHAR2(50), 
	TEACHER_ID NUMBER, 
	 PRIMARY KEY (CLASS_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE, 
	 FOREIGN KEY (TEACHER_ID)
	  REFERENCES BRAIN_WAVE_DBA_INTERN.TEACHERS (TEACHER_ID) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS;

  CREATE TABLE BRAIN_WAVE_DBA_INTERN.ENROLLMENT 
   (	ENROLLMENT_ID NUMBER, 
	STUDENT_ID NUMBER, 
	CLASS_ID NUMBER, 
	ENROLLMENT_DATE DATE, 
	 PRIMARY KEY (ENROLLMENT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE, 
	 FOREIGN KEY (STUDENT_ID)
	  REFERENCES BRAIN_WAVE_DBA_INTERN.STUDENTS (STUDENT_ID) ENABLE, 
	 FOREIGN KEY (CLASS_ID)
	  REFERENCES BRAIN_WAVE_DBA_INTERN.CLASSES (CLASS_ID) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS;

  CREATE TABLE BRAIN_WAVE_DBA_INTERN.ATTENDANCE 
   (	ATTENDANCE_ID NUMBER, 
	STUDENT_ID NUMBER, 
	CLASS_ID NUMBER, 
	ATTENDANCE_DATE DATE, 
	STATUS VARCHAR2(10), 
	 PRIMARY KEY (ATTENDANCE_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE, 
	 FOREIGN KEY (STUDENT_ID)
	  REFERENCES BRAIN_WAVE_DBA_INTERN.STUDENTS (STUDENT_ID) ENABLE, 
	 FOREIGN KEY (CLASS_ID)
	  REFERENCES BRAIN_WAVE_DBA_INTERN.CLASSES (CLASS_ID) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS;

  CREATE TABLE BRAIN_WAVE_DBA_INTERN.EXAMS 
   (	EXAM_ID NUMBER, 
	SUBJECT_ID NUMBER, 
	CLASS_ID NUMBER, 
	EXAM_DATE DATE, 
	TOTAL_MARKS NUMBER, 
	 PRIMARY KEY (EXAM_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE, 
	 FOREIGN KEY (SUBJECT_ID)
	  REFERENCES BRAIN_WAVE_DBA_INTERN.SUBJECTS (SUBJECT_ID) ENABLE, 
	 FOREIGN KEY (CLASS_ID)
	  REFERENCES BRAIN_WAVE_DBA_INTERN.CLASSES (CLASS_ID) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS;

  CREATE TABLE BRAIN_WAVE_DBA_INTERN.FEES 
   (	PAYMENT_ID NUMBER, 
	STUDENT_ID NUMBER, 
	AMOUNT_PAID NUMBER, 
	PAYMENT_DATE DATE, 
	 PRIMARY KEY (PAYMENT_ID)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE, 
	 FOREIGN KEY (STUDENT_ID)
	  REFERENCES BRAIN_WAVE_DBA_INTERN.STUDENTS (STUDENT_ID) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS;
